#version 460
#extension GL_EXT_nonuniform_qualifier: require

layout (local_size_x = 16, local_size_y = 16) in;


layout (set = 0, binding = 0) uniform sampler2D bloomImage;    // Blurred Mips (Mip 1)
layout (set = 0, binding = 1, rgba16f) writeonly uniform image2D outputImage; // Target (Mip 0)
layout (set = 0, binding = 2) uniform sampler2D originalScene; // NEW: The clean scene

layout (set = 1, binding = 0) uniform sampler2D samplerImages[];


layout (push_constant) uniform PushConstant {
    float exposure;
    float bloomStrength;
    int dirtImageIdx;
} pc;

void main() {
    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(outputImage);
    if (pixelCoords.x >= size.x || pixelCoords.y >= size.y) return;

    vec2 uv = (vec2(pixelCoords) + 0.5) / vec2(size);

    vec3 sceneColor = texture(originalScene, uv).rgb; 
    
    vec3 bloomData = texture(bloomImage, uv).rgb;
    vec3 dirtMask = texture(samplerImages[pc.dirtImageIdx], uv).rgb;
    vec3 lensFlareEffect = bloomData * dirtMask;

    vec3 totalBloomContribution = (bloomData + lensFlareEffect) * pc.bloomStrength;
    vec3 finalLinearColor = sceneColor + totalBloomContribution;

    imageStore(outputImage, pixelCoords, vec4(finalLinearColor, 1.0));
}