#version 450
layout(local_size_x = 256) in;

layout(std430, binding = 1) buffer PartialSums { vec4 partials[]; };
layout(std430, binding = 2) buffer FinalSH { vec4 finalCoeffs[9]; };

shared vec4 s_sum[9][256];

void main() {
    uint tid = gl_LocalInvocationIndex;
    uint numPartials = 2048; 

    for(int i = 0; i < 9; i++) {
        s_sum[i][tid] = vec4(0.0);
    }

    for (uint i = tid; i < numPartials; i += 256) {
        for(int j = 0; j < 9; j++) {
            s_sum[j][tid] += partials[i * 9 + j];
        }
    }
    barrier();

    for (uint s = 128; s > 0; s >>= 1) {
        if (tid < s) {
            for(int j = 0; j < 9; j++) {
                s_sum[j][tid] += s_sum[j][tid + s];
            }
        }
        barrier();
    }

    if (tid == 0) {
        for(int j = 0; j < 9; j++) {
            finalCoeffs[j] = s_sum[j][0];
        }
    }
}