#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_nonuniform_qualifier : enable

struct RayPayload {
    vec3 hitPos;
    vec3 bc;
    int instanceIndex;
    int primitiveIndex;
    uint hit;
    uint seed;
};

struct Material {
    uint albedoIdx;
    uint normalIdx;
    uint metalnessIdx;
    uint roughnessIdx;
    uint aoIdx;
    uint emissiveIdx;

    vec2 uvOffset;
    vec4 albedoFactor;
    vec4 normalFactor;
    float metallicFactor;
    float roughnessFactor;
    float aoFactor;
    float emissiveFactor;
};

const uint MAX_BONE_INFLUENCE =  4;
const float PI = 3.14159265359;

struct Vertex {
    vec3 pos; 
    vec3 col; 
    vec2 uv; 
    vec3 normal; 
    vec3 tangent; 
    vec3 biTangent;
    int m_BoneIDs[MAX_BONE_INFLUENCE]; 
    float m_Weights[MAX_BONE_INFLUENCE];
};

struct Object {
    uint64_t vertexAddress; 
    uint64_t indexAddress;
    uint64_t materialsRef; 
    uint64_t materialIndiciesRef;
};


layout(location = 0) rayPayloadEXT RayPayload payload;

layout(set = 0, binding = 0) uniform accelerationStructureEXT topLevelAS;
layout(set = 0, binding = 1, rgba16f) uniform image2D outputImage;
layout(set = 0, binding = 2) uniform UniformBufferObject {
    mat4 view;
    mat4 prevViewProj;
    mat4 proj;
    vec4 cameraPos;
    mat4 invView;
    mat4 invProj;
    float width;
    float height;
    float frameSeed;
    int frameCount;
    bool accumulate;
} ubo;

layout(set = 1, binding = 0) uniform sampler2D samplerImages[];


layout(buffer_reference, scalar) buffer ObjectsBuffer { Object objects[]; };
layout(buffer_reference, scalar) buffer Vertices { Vertex v[]; };
layout(buffer_reference, scalar) buffer Indices { uint i[]; };
layout(buffer_reference, scalar) buffer MaterialsBuffer { Material m[]; };
layout(buffer_reference, scalar) readonly buffer MatIndicesBuffer { uint i[]; };

layout(push_constant) uniform PushConstant {
    ObjectsBuffer objRef;
    uint objIdx;
} pc;


uint pcg_hash(uint inSeed) {
    uint state = inSeed * 747796405u + 2891336453u;
    uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
    return (word >> 22u) ^ word;
}

float rnd(inout uint seed) {
    seed = pcg_hash(seed);
    return float(seed) * (1.0 / 4294967296.0);
}

// Function to get a random rayDir in a hemisphere
vec3 samplingHemisphere(vec3 normal, inout uint seed) {
    float phi = 2.0 * 3.14159265 * rnd(seed);
    float cosTheta = rnd(seed);
    float sinTheta = sqrt(1.0 - cosTheta * cosTheta);
    
    vec3 tangent = normalize(cross(normal, abs(normal.x) > 0.1 ? vec3(0, 1, 0) : vec3(1, 0, 0)));
    vec3 bitangent = cross(normal, tangent);
    
    return tangent * (cos(phi) * sinTheta) + bitangent * (sin(phi) * sinTheta) + normal * cosTheta;
}


void getHitObjectData(out Material mat, out vec3 nrm)
{
    Object obj = pc.objRef.objects[payload.instanceIndex];
    
    // dereference addresses
    Vertices vertices = Vertices(obj.vertexAddress);
    Indices indices = Indices(obj.indexAddress);
    MaterialsBuffer materials = MaterialsBuffer(obj.materialsRef);
    MatIndicesBuffer matIndices = MatIndicesBuffer(obj.materialIndiciesRef);
  
    // Use gl_PrimitiveID to access the triangle's vertices and material
    uint i0 = indices.i[3 * payload.primitiveIndex + 0];    // flatten triangle hit indices
    uint i1 = indices.i[3 * payload.primitiveIndex + 1];
    uint i2 = indices.i[3 * payload.primitiveIndex + 2];

    uint matIdx   = matIndices.i[payload.primitiveIndex];    // triangles material index
    mat = materials.m[matIdx];                              // triangles material

    // Vertex of the triangle (Vertex has pos, nrm, tex)
    Vertex v0 = vertices.v[i0];
    Vertex v1 = vertices.v[i1];
    Vertex v2 = vertices.v[i2];

    // Compute normal at hit position using the provided barycentric coordinates.
    const vec3 bc = payload.bc;                                 // The barycentric coordinates of the hit point
    nrm  = bc.x*v0.normal + bc.y*v1.normal + bc.z*v2.normal;    // Normal = combo of three vertex normals

    // If the material has a texture, read texture and use as the point's diffuse color.
    if (mat.albedoIdx != uint(0)) {
        vec2 uv =  bc.x*v0.uv + bc.y*v1.uv + bc.z*v2.uv;
        mat.albedoFactor = texture(samplerImages[(mat.albedoIdx)], uv);
    }
}

uint tea(uint val0, uint val1)
{
  uint v0 = val0;
  uint v1 = val1;
  uint s0 = 0;

  for(uint n = 0; n < 16; n++)
  {
    s0 += 0x9e3779b9;
    v0 += ((v1 << 4) + 0xa341316c) ^ (v1 + s0) ^ ((v1 >> 5) + 0xc8013ea4);
    v1 += ((v0 << 4) + 0xad90777d) ^ (v0 + s0) ^ ((v0 >> 5) + 0x7e95761e);
  }

  return v0;
}

vec3 toTangentSpace(vec3 v, vec3 N) {
    vec3 up = abs(N.z) < 0.999 ? vec3(0,0,1) : vec3(1,0,0);
    vec3 tangentX = normalize(cross(up, N));
    vec3 tangentY = cross(N, tangentX);

    return v.x * tangentX + v.y * tangentY + v.z * N;
}

vec3 SampleLobe(vec3 N, float r1, float r2) {
    float s = sqrt(1 - r1 * r1);
    vec3 k = vec3(s*cos(r2), s*sin(r2), r1);
    k = toTangentSpace(k, N);

    return k;
}

vec3 SampleBrdf(inout uint seed, in vec3 N) {
    float r1 = sqrt(rnd(seed));
    float r2 = float(2*PI*rnd(seed));
    vec3 Wi = SampleLobe(N, r1, r2);

    return normalize(Wi);
    return Wi;
}

float PdfBrdf(vec3 N, vec3 L) {
    return max(dot(N, L), 0.0) / PI;
}

// D factor
float DistributionGGX(vec3 N, vec3 H, float alphaRoughness) {
    float NdotH = max(dot(N, H), 0.0);
    float a2 = alphaRoughness * alphaRoughness;
    float NdotH2 = NdotH * NdotH;
    
    float numerator = a2;
    float denominator = (NdotH2 * (a2 - 1.0) + 1.0);
    float D = numerator / (PI * denominator * denominator);
    
    return D;
}

// F factor
vec3 Fresnel(vec3 Ks, float d) {
    // return Ks + (1 - Ks) * pow(1 - abs(d), 5);
    return Ks + (1 - Ks) * pow(clamp(1.0 - d, 0.0, 1.0), 5);
}

float SchlickGGX(float NdotV, float alphaRoughness) {
    float r = (alphaRoughness + 1.0);
    float k = (r*r) / 8.0;

    float numerator   = NdotV;
    float denominator = NdotV * (1.0 - k) + k;
	
    return numerator / denominator;
}

//G factor
float GGXSmith(float NdotV, float NdotL, float alphaRoughness) {
    float GV = SchlickGGX(NdotV, alphaRoughness);
    float GL = SchlickGGX(NdotL, alphaRoughness);
    
    return GV * GL;
}

vec3 CookTorranceSpecular(vec3 N, vec3 V, vec3 L, vec3 Ks, float alphaRoughness) {
    vec3 H = normalize(V + L);
    
    float NdotV = max(dot(N, V), 0.0);
    float NdotL = max(dot(N, L), 0.0);
    float NdotH = max(dot(N, H), 0.0);
    float VdotH = max(dot(V, H), 0.0);

    float D = DistributionGGX(N, H, alphaRoughness);
    vec3 F = Fresnel(Ks, VdotH);
    float G = GGXSmith(NdotV, NdotL, alphaRoughness);

    return (D * F * G) / (4.0 * NdotV * NdotL + 1e-5);
}

void main() {
    ivec2 pixelCoords = ivec2(gl_LaunchIDEXT.xy);
    vec2 pixelUV = (vec2(pixelCoords) + 0.5) / vec2(gl_LaunchSizeEXT.xy);
    vec2 d = pixelUV * 2.0 - 1.0;

    vec4 rayOrigin = ubo.invView * vec4(0, 0, 0, 1);
    vec4 target = ubo.invProj * vec4(d.x, d.y, 1.0, 1.0);
    vec3 rayDir = vec3(ubo.invView * vec4(normalize(target.xyz), 0));
    uint seed = pcg_hash(pixelCoords.y * uint(ubo.width) + pixelCoords.x + pcg_hash(uint(ubo.frameSeed)));
    vec3 accumulation = vec3(0.0);
    vec3 throughput = vec3(1.0);
    
    vec3 C = vec3(0,0,0);
    vec3 W = vec3(1,1,1);   // path tracing algorithm accumulates a product of f/p weights in W.
    payload.seed = tea(gl_LaunchIDEXT.y * gl_LaunchSizeEXT.x + gl_LaunchIDEXT.x, uint(ubo.frameSeed));
    

    const int numBounces = 4;
    for (int i = 0; i < 4; i++) {
        payload.hit = 0;

        // Fire the ray;  hit or miss shaders will be invoked, passing results back in the payload
        traceRayEXT(topLevelAS, gl_RayFlagsOpaqueEXT, 0xFF, 0, 0, 0, rayOrigin.xyz, 0.001, rayDir, 10000.0, 0);
        // traceRayEXT(
        //     topLevelAS,           // tlas acceleration structure
        //     gl_RayFlagsOpaqueEXT, // rayFlags
        //     0xFF,                 // cullMask
        //     0,                    // sbtRecordOffset for the hitgroups
        //     0,                    // sbtRecordStride for the hitgroups
        //     0,                    // missIndex
        //     rayOrigin.xyz,            // ray origin
        //     0.001,                // ray min range
        //     rayDir,         // ray direction
        //     10000.0,              // ray max range
        //     0                     // payload (location = 0)
        // );

        if (payload.hit == 0) {
            // accumulation += vec3(0.1, 0.2, 0.3);
            break;
        }
        
        Material mat;
        vec3 nrm;
        getHitObjectData(mat, nrm);

        if(mat.emissiveFactor >= 0.01) {
            Object obj = pc.objRef.objects[payload.instanceIndex];
                
            // dereference addresses
            Vertices vertices = Vertices(obj.vertexAddress);
            Indices indices = Indices(obj.indexAddress);
            MaterialsBuffer materials = MaterialsBuffer(obj.materialsRef);
            MatIndicesBuffer matIndices = MatIndicesBuffer(obj.materialIndiciesRef);
        
            // Use gl_PrimitiveID to access the triangle's vertices and material
            uint i0 = indices.i[3 * payload.primitiveIndex + 0];    // flatten triangle hit indices
            uint i1 = indices.i[3 * payload.primitiveIndex + 1];
            uint i2 = indices.i[3 * payload.primitiveIndex + 2];

            uint matIdx   = matIndices.i[payload.primitiveIndex];    // triangles material index
            mat = materials.m[matIdx];                              // triangles material

            // Vertex of the triangle (Vertex has pos, nrm, tex)
            Vertex v0 = vertices.v[i0];
            Vertex v1 = vertices.v[i1];
            Vertex v2 = vertices.v[i2];

            // Compute normal at hit position using the provided barycentric coordinates.
            const vec3 bc = payload.bc;                                 // The barycentric coordinates of the hit point
            nrm  = bc.x*v0.normal + bc.y*v1.normal + bc.z*v2.normal;    // Normal = combo of three vertex normals

            vec3 emissiveColor = mat.albedoFactor.rgb;
            // If the material has emissive texture
            if (mat.emissiveIdx != uint(0)) {
                vec2 uv =  bc.x*v0.uv + bc.y*v1.uv + bc.z*v2.uv;
                emissiveColor = texture(samplerImages[(mat.emissiveIdx)], uv).rgb;
            }

            C += W * emissiveColor * mat.emissiveFactor;
            // C += W * emissive * mat.emissiveFactor;// * 0.5; // 0.5 for explicit ray
        }

        payload.hit = 1;
        
        /*
        if(ubo.explicitPass) {
        
        }
        */

        vec3 N = normalize(nrm);
        vec3 Wi = SampleBrdf(payload.seed, N);             
        vec3 Wo  = -rayDir;

        vec3 diffuse = mat.albedoFactor.xyz / PI;
        vec3 F0 = vec3(0.04);               // simple approximation
        vec3 specular = CookTorranceSpecular(N, Wi, Wo, F0, mat.roughnessFactor);
        vec3 f = (diffuse + specular) * max(dot(N, Wi), 0.0);
        // vec3 f  = dot(N, Wi) * EvalBrdf(N, Wi, Wo, mat);

        float p = PdfBrdf(N, Wi);    

        W *= f / p;                                      
        rayOrigin = vec4(payload.hitPos + 0.001 * N, 1.0);
        rayDir = Wi;  
    }
    vec4 old = imageLoad(outputImage, pixelCoords);
    vec3 Ave = old.xyz;
    float N = old.w;

    if(ubo.accumulate) {
        Ave = vec3(0.0);
        N = 0.0;        
        imageStore(outputImage, pixelCoords, vec4(Ave, N));
    }

    Ave += (C - Ave)/(N + 1);
    N += 1;
    imageStore(outputImage, pixelCoords, vec4(Ave, N));
}