#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_nonuniform_qualifier : enable

struct RayPayload {
    vec3 hitPos;
    vec3 bc;
    int instanceIndex;
    int primitiveIndex;
    uint hit;
    uint seed;
};

layout(location = 0) rayPayloadEXT RayPayload payload;

layout(set = 0, binding = 0) uniform accelerationStructureEXT topLevelAS;
layout(set = 0, binding = 1, rgba16f) uniform image2D outputImage;
layout(set = 0, binding = 2) uniform UniformBufferObject {
    mat4 view; mat4 prevViewProj; mat4 proj; vec4 cameraPos;
    mat4 invView; mat4 invProj; float width; float height;
} ubo;

void main() {
    ivec2 pixelCoords = ivec2(gl_LaunchIDEXT.xy);
    vec2 uv = (vec2(pixelCoords) + 0.5) / vec2(gl_LaunchSizeEXT.xy);
    vec2 d = uv * 2.0 - 1.0;

    vec4 origin = ubo.invView * vec4(0, 0, 0, 1);
    vec4 target = ubo.invProj * vec4(d.x, d.y, 1.0, 1.0);
    vec3 direction = vec3(ubo.invView * vec4(normalize(target.xyz), 0));

    payload.hitPos = vec3(0.0);
    payload.hit = 0;

    traceRayEXT(topLevelAS, gl_RayFlagsOpaqueEXT, 0xFF, 0, 0, 0, origin.xyz, 0.001, direction, 10000.0, 0);

    imageStore(outputImage, pixelCoords, vec4(payload.hitPos, 1.0));
}